#服务配置
server:
  port: 20002
  servlet:
    context-path: /

spring:
  application:
    name: kafka-producer

  kafka:
    bootstrap-servers: 127.0.0.1:9092
    consumer:
      group-id: ms
      auto-offset-reset: earliest
    listener:
      missing-topics-fatal: false



